### ISSUE TITLE
Infinite loop of caching failed on some images and all following new images 

### ISSUE THREAD

**Issue by rucciva** [enix/kube-image-keeper#124]
Hi , i'm currently running kuik 1.20 with s3 backend and noticed several imaged failed to be cached with the following event:

```
│ Events:                                                                                                                            │
│   Type     Reason       Age                     From                    Message                                                    │
│   ----     ------       ----                    ----                    -------                                                    │
│   Normal   Caching      6m11s (x300 over 3d9h)  cachedimage-controller  Start caching image docker.io/bitnami/redis:6.2.10-debian-11-r13                                                                                                                             │
│   Warning  CacheFailed  6m9s (x300 over 3d9h)   cachedimage-controller  Failed to cache image docker.io/bitnami/redis:6.2.10-debian-11-r13, reason: POST http://kube-image-keeper-registry:5000/v2/docker.io/bitnami/redis/blobs/uploads/: unexpected status code 405 Method Not Allowed: Method not allowed   
```

Restarting the controller or registry pod doesn't seem to fix it. I've also tried deleting the cached image but same result. 

The only workaround that seems to solve it was to uninstall kuik, delete the s3 bucket, and reinstall it. But soon when an image fail to be cached, all new image can no longer be cached.

**Comment by paullaffitte** [comment]
Hello, thanks for reaching us

I've tried to reproduce your issue using the same image, but I couldn't. I have a few questions to try to understand better:

- When you says `kuik 1.20`, do you mean `kubernetes 1.20`?
- What version of kuik are you using?
- Do you reproduce with persistence disabled?
- Could you share your `values.yaml`?

**Comment by rucciva** [comment]
> When you says kuik 1.20, do you mean kubernetes 1.20?
i'm sorry, i mean kuik 1.2.0, i'm using kuberenetes 1.23

> What version of kuik are you using?
1.2.0

> Do you reproduce with persistence disabled
i haven't tried it with persistence

> Could you share your values.yaml?

```
controllers:
  image:
    repository: quay.io/enix/kube-image-keeper

proxy:
  image:
    repository: quay.io/enix/kube-image-keeper

registry:
  persistence:
    s3:
      regionendpoint: "obs.ap-southeast-4.myhuaweicloud.com"
      region: "ap-southeast-4"
      bucket: "some-bucket"
      rootdirectory: /support/prod
    s3ExistingSecret: kube-image-keeper
```
