### ISSUE TITLE
Support for registry 307 response (S3 storage)

### ISSUE THREAD

**Issue by Tefnet** [enix/kube-image-keeper#142]
Right now it looks like proxy doesn't support 307 responses.

"cached image is not available, proxying origin" originRegistry="541519999999.dkr.ecr.us-west-2.amazonaws.com" error="307 Temporary Redirect"

When using S3 storage, registry, by default, is responding with 307 redirect directly to S3 bucket, to avoid proxy image layers through the service.
https://docs.docker.com/registry/spec/api/#pulling-a-layer

It would be great if kube-image-keeper proxy could support 307 and forward it to the client, to directly fetch the image from the S3. It's not only faster, but also cheaper (S3->EC2 is free, while EC2->EC2 in different AZs is not).

As a workaround, for now it's possible to disable redirects by setting in helm values:
```
    registry:
      env:
      - name: REGISTRY_STORAGE_REDIRECT_DISABLE
        value: true
```
