### ISSUE TITLE
MutatingWebHook generates invalid annotations

### ISSUE THREAD

**Issue by npdgm** [enix/kube-image-keeper#143]
With a container having a long name, the MutatingWebHook will generate an invalid Pod object.

Example Deployment:
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test
  template:
    metadata:
      labels:
        app: test
    spec:
      containers:
      - name: aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
        image: nginx
```

The ReplicatSet is stuck and no workload can start:
```
Error creating: Pod "test-57ccc945b8-g94d9" is invalid: metadata.annotations: Invalid value: `"original-image-aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa":` name part must be no more than 63 characters
```
