### ISSUE TITLE
sourceImage url with custom port issue

### ISSUE THREAD

**Issue by dm-jnpstr** [enix/kube-image-keeper#223]
We are experiencing an issue with caching images from a private GitLab registry operating on a custom port (the registry is hosted at gitlab.example.com:5050). The error encountered is as follows:

`Failed to cache image gitlab.example.com-5050/group/image/101-tests:87cb4002, due to the following reason: Get 'https://gitlab.example.com-5050/v2/': dial TCP: lookup gitlab.example.com-5050 on 10.3.0.10:53: no such host found; Get 'http://gitlab.example.com-5050/v2/': dial TCP: lookup gitlab.example.com-5050 on 10.3.0.10:53: no such host found.`

It appears that the issue is related to the CRD where the 'sourceImage' field incorrectly replaces ':' with '-'. For reference, here is an example of the CRD (redacted):

```YAML
apiVersion: kuik.enix.io/v1alpha1
kind: CachedImage
metadata:
  creationTimestamp: '2023-11-29T14:18:02Z'
  finalizers:
    - cachedimage.kuik.enix.io/finalizer
  generation: 2
  labels:
    kuik.enix.io/repository: 1dbfc7ee32cce8bf16cb315a49504c0ff229eabcf51bd9baf71c6f36
status:
  usedBy:
    count: 1
    pods:
      - namespacedName: test/preview-test-migration-x7bqg
spec:
  pullSecretNames:
    - preview-48131-test-registry
  pullSecretsNamespace: test
  sourceImage: >-
    gitlab.example.com-5050/group/image/101-tests:87cb4002
```

**Comment by paullaffitte** [comment]
Hello,

What version of kuik are you using ?

**Comment by dm-jnpstr** [comment]
Here is example when even crd not created (on our production cluster), but at events i see:

```
kubectl run test --image gitlab.example.com-5050/example/example-manage/101-feat-add-example-helper-for-tests:87cb4002

Failed to pull image "gitlab.example.com-5050/example/example-manage/101-feat-add-example-helper-for-tests:87cb4002": rpc error: code = Unknown desc = failed to pull and unpack image "gitlab.example.com-5050/example/example-manage/101-feat-add-example-helper-for-tests:87cb4002": failed to resolve reference "gitlab.example.com-5050/example/example-manage/101-feat-add-example-helper-for-tests:87cb4002": failed to do request: Head "gitlab.example.com-5050/example/example-manage/101-feat-add-example-helper-for-tests:87cb4002": dial tcp: lookup gitlab.example.com-5050 on redacted_ip:53: no such host
```

At stage cluster crd created, but issue with sourceImage persist:

```
apiVersion: kuik.enix.io/v1alpha1
kind: CachedImage
metadata:
  creationTimestamp: '2023-11-29T14:18:02Z'
  finalizers:
    - cachedimage.kuik.enix.io/finalizer
  generation: 2
  labels:
    kuik.enix.io/repository: 1dbfc7ee32cce8bf16cb315a49504c0ff229eabcf51bd9baf71c6f3
status:
  usedBy:
    count: 1
    pods:
      - namespacedName: test/preview-test48131-migration-x7bqg
spec:
  pullSecretNames:
    - preview-test48131-jnpstr-registry
  pullSecretsNamespace: prro
  sourceImage: >-
    gitlab.example.com-5050/example/example-manage/101-feat-add-example-helper-for-tests:87cb4002
```

Events:


`3m20s       Normal    Scheduled   pod/test   Successfully assigned example/test to infrastructure-services-nodepo-node-6eaeee
107s        Normal    Pulling     pod/test   Pulling image "gitlab.example.com-5050/example/example-manage/101-feat-add-example-helper-for-tests:87cb4002"
107s        Warning   Failed      pod/test   Failed to pull image "gitlab.example.com-5050/example/example-manage/101-feat-add-example-helper-for-tests:87cb4002": rpc error: code = Unknown desc = failed to pull and unpack image "gitlab.example.com-5050/example/example-manage/101-feat-add-example-helper-for-tests:87cb4002": failed to resolve reference "gitlab.example.com-5050/example/example-manage/101-feat-add-example-helper-for-tests:87cb4002": failed to do request: Head "https://gitlab.example.com-5050/v2/example/example-manage/101-feat-add-example-helper-for-tests/manifests/87cb4002": dial tcp: lookup gitlab.example.com-5050 on redacted_ip:53: no such host
107s        Warning   Failed      pod/test   Error: ErrImagePull
93s         Normal    BackOff     pod/test   Back-off pulling image "gitlab.example.com-5050/example/example-manage/101-feat-add-example-helper-for-tests:87cb4002"
2m1s        Warning   Failed      pod/test   Error: ImagePullBackOff
`

If i change SourceImage:
from gitlab.example.com-5050/example/example-manage/101-feat-add-example-helper-for-tests:87cb4002 to gitlab.example.com:5050/example/example-manage/101-feat-add-example-helper-for-tests:87cb4002 all working as expected
