### ISSUE TITLE
Unable to fetch private repositories - Unauthorized

### ISSUE THREAD

**Issue by Rohithzr** [enix/kube-image-keeper#276]
This is the error I am getting: 

```
cache-manager 2024-02-15T12:34:59.826Z      ERROR   Reconciler error        {"controller": "cachedimage", "controllerGroup": "kuik.enix.io", "controllerKind": "CachedImage", "CachedImage": {"name":"llmtuner-001-a7d92bc294e2fe8ec6eae13e613ed95fa2812ccafd3b888c162798db46641c90"}, "namespace": "", "name": "llmtuner-001-a7d92bc294e2fe8ec6eae13e613ed95fa2812ccafd3b888c162798db46641c90", "reconcileID": "85047ace-557f-4c1c-9016-78c5b031c297", "error": "GET https://index.docker.io/v2/<org-name>/foundation-inference-llmtuner-001-development/manifests/sha256:a7d92bc294e2fe8ec6eae13e613ed95fa2812ccafd3b888c162798db46641c90: UNAUTHORIZED: authentication required; [map[Action:pull Class: Name:<org-name>/foundation-inference-llmtuner-001-development Type:repository]]", "errorCauses": [{"error": "GET https://index.docker.io/v2/<org-name>/foundation-inference-llmtuner-001-development/manifests/sha256:a7d92bc294e2fe8ec6eae13e613ed95fa2812ccafd3b888c162798db46641c90: UNAUTHORIZED: authentication required; [map[Action:pull Class: Name:<org-name>/foundation-inference-llmtuner-001-development Type:repository]]"}]}
```

My pod has an imagePullSecrets pre-defined and is successfully pulling the image from docker hub.

here is my helm release values:

```
   controllers:
      replicas: 3
      imagePullSecrets:
        - name: regcred
      webhooks:
        ignoredNamespaces:
          - kube-system
          - kuik
    registry:
      replicas: 3
      imagePullSecrets:
        - name: regcred
      persistence:
        enabled: false
        s3:
          enabled: true
          region: "gra"
          bucket: "kuik-registry"
          endpoint_url: "https://s3.gra.perf.cloud.ovh.net/"
          regionendpoint: "https://s3.gra.perf.cloud.ovh.net/"
          skip_credentials_validation: true
          skip_region_validation: true
        s3ExistingSecret: "kuik-secret"
    registryUI:
      enabled: true
      imagePullSecrets:
        - name: regcred
```
