### ISSUE TITLE
registry needs a configured S3 endpoint to enable HA mode

### ISSUE THREAD

**Issue by felipewnp** [enix/kube-image-keeper#279]
Hi.

I'm having the following problem when installing kuik with `ReadWriteMany` and `replica > 1`

`Error: execution error at (kube-image-keeper/templates/registry-statefulset.yaml:4:3): registry needs a configured S3 endpoint to enable HA mode (>1 replicas), please enable minio or configure an external S3 endpoint`

This is my kuik helm values.yaml file (the registry part):

```yaml
registry:
  affinity:
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchExpressions:
              - key: app.kubernetes.io/component
                operator: In
                values:
                  - registry
              - key: app.kubernetes.io/name
                operator: In
                values:
                  - kube-image-keeper
          topologyKey: failure-domain.beta.kubernetes.io/zone
  replicas: 2
  nodeSelector:
    intent: system
  pdb:
    create: true
    minAvailable: 1
  persistence:
    enabled: true
    accessModes: "ReadWriteMany"
    size: 1Gi # EFS doesn't have size parameter
    storageClass: efs
  priorityClassName: system-cluster-critical
```

Have I done something wrong? Or are the docs outdated?

At [this link](https://github.com/enix/kube-image-keeper/blob/main/docs/high-availability.md), It says that kuik HA works with ReadWriteMany and EFS.

Also, I'm only using EFS because I'm afraid of transfer costs from S3 to kuik. Does that (transfer) usually happen a lot?
