### ISSUE TITLE
when you change the hostport in helm configuration the probe port doesn't change

### ISSUE THREAD

**Issue by didlawowo** [enix/kube-image-keeper#299]
il have changed the hostport configuration in helm value, to another port, 
but the readyness always check the default port, then the proxy doesn't start and cluster get imagepullbackoff

should be nice to fix that
and ensure proxy is running before mutating webhook activation, because it can stuck an entire cluster . 

then i restore the config default for port but the pod stuck doesn't work (before my hostport was 8439, the problem appear since 1.6 and 1.7 don't fix it 

```                                                                                 │
│   Normal   Scheduled  2m34s                default-scheduler  Successfully assigned kube-infra/neuvector-controller-pod-698577675b-9z8c9 to master              │
│   Normal   Pulling    65s (x4 over 2m33s)  kubelet            Pulling image "localhost:7439/docker.io/neuvector/controller:5.3.0"                               │
│   Warning  Failed     65s (x4 over 2m33s)  kubelet            Failed to pull image "localhost:7439/docker.io/neuvector/controller:5.3.0": failed to pull and un │
│ pack image "localhost:7439/docker.io/neuvector/controller:5.3.0": failed to resolve reference "localhost:7439/docker.io/neuvector/controller:5.3.0": failed to  │
│ do request: Head "https://localhost:7439/v2/docker.io/neuvector/controller/manifests/5.3.0": dial tcp [::1]:7439: connect: connection refused                   │
│   Warning  Failed     65s (x4 over 2m33s)  kubelet            Error: ErrImagePull                                                                               │
│   Warning  Failed     51s (x6 over 2m33s)  kubelet            Error: ImagePullBackOff                                                                           │
│   Normal   BackOff    36s (x7 over 2m33s)  kubelet            Back-off pulling image "localhost:7439/docker.io/neuvector/controller:5.3.0"   
```

**Comment by didlawowo** [comment]
my configuration 
```
registryUI:
  nodeSelector:
    kubernetes.io/arch: amd64
  enabled: true
  auth:
    username: admin
    password: adminRegistry
proxy:
  resources:
    limits:
      cpu: 300m
      memory: 256Mi
cachedImagesExpiryDelay: 10
controllers:
  resources:
    limits:
      cpu: 200m
      memory: 256Mi
  pdb:
    create: true
    minAvailable: 1
  webhook:
    ignoredNamespaces:
    - kube-system
    - kube-node-lease
    - crossplane-system
    - keeper
    - kube-infra
    - kube-monitoring
    - longhorn-system
    - security

```

**Comment by bgandon** [comment]
When you align the value of `proxy.readinessProbe.httpGet.port` to your custom `8439` value for `hostPort`, does it fix the problem?

Or else, is sticking to the default `7439` value a blocker for you?

**Comment by didlawowo** [comment]
i have rollbacked with the original port and its the same problem

**Comment by didlawowo** [comment]
i'm using cilium and longhorn on both config

**Comment by Nicolasgouze** [comment]
hi @didlawowo , 

* Can you please elaborate a bit more regarding your "rollback" operation ? 
* Did you try to deploy again setting the same value for proxy.readinessProbe.httpGet.port & proxy.hostPort ?
* Can you please dump here the proxy daemonset configuration ? 
* Can you please specify your cilium config ? Did you enable the portMapping plugin ?

**Comment by didlawowo** [comment]
i do that tomorrow.

**Comment by didlawowo** [comment]
i have installed the latest version on a new rke2 cluster with cilium (no portmap)
seems OK 

the cilium config:

```
apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: rke2-cilium
  namespace: kube-system
spec:
  valuesContent: |-
    eni:
      enabled: true
    kubeProxyReplacement: "strict"
    k8sServiceHost: 127.0.0.1
    k8sServicePort: 6443
    global:
      bpf:
        masquerade: true
    cni:
      chainingMode: "none"
    operator:
      replicas: 2
    encryption:
      enabled: true
      type: wireguard
    l7Proxy: false
    hubble:
      enabled: true
      metrics:
        enableOpenMetrics: true
        enabled:
        - dns:query;ignoreAAAA
        - drop
        - tcp
        - flow
        - icmp
        - http

      relay:
        enabled: true
      ui:
        enabled: true
        replicas: 1
        ingress:
          enabled: true
          hosts:
            - hubble.develop.oursain.net
          annotations:
            cert-manager.io/cluster-issuer: letsencrypt
          tls:
          - secretName: ingress-hubble-ui-tls
            hosts:
            - hubble.develop.oursain.net
    prometheus:
      enabled: true
```
