### ISSUE TITLE
cronjob garbage-collection can't be resources specified

### ISSUE THREAD

**Issue by RogerSik** [enix/kube-image-keeper#359]
For the cronjob I can't specificy 
```yaml
          resources:
            limits:
              memory: 200Mi
            requests:
              cpu: 10m
              memory: 100Mi
```

because i have in every namespace ResourceQuota enabled (enforcement of use of resources.limits and resources.requests) the pod is failing queitly (no scheduling of the pod).

**Comment by RogerSik** [comment]
A workaround is to use LimitRange. For everyone who is struggling with the same issue: 

```yaml
apiVersion: v1
kind: LimitRange
metadata:
  name: kuik
  namespace: kuik
spec:
  limits:
    - default:
        memory: 200Mi
      defaultRequest:
        cpu: 10m
        memory: 100Mi
      type: Container

```
