### ISSUE TITLE
AWS EKS IRSA ServiceAccount

### ISSUE THREAD

**Issue by grzegorzgniadekrespo** [enix/kube-image-keeper#486]
Hi, i got problem when i deploy kuik with serviceAccount Annotations with enabled AWS EKS IRSA 
Config
```
serviceAccount:
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::112233445566:role/dev-eks-kube-image-keeperall@kuik-system
registry:
  serviceAccount:
    annotations:
      eks.amazonaws.com/role-arn: arn:aws:iam::112233445566:role/dev-eks-kube-image-keeperall@kuik-system
  persistence:
    s3:
      region: "eu-central-1"
      accesskey: ""
      secretkey: ""
      loglevel: "debugwithsigning"
      bucket: kuik-testing
controllers:
  serviceAccount:
    annotations:
      eks.amazonaws.com/role-arn: arn:aws:iam::112233445566:role/dev-eks-kube-image-keeperall@kuik-system
```
Error Log
```
time="2025-03-24T19:43:00.887950998Z" level=error msg="response completed with error" err.code=unknown err.detail="s3aws: NoCredentialProviders: no valid providers in chain. Deprecated.
        For verbose messaging see aws.Config.CredentialsChainVerboseErrors" err.message="unknown error" go.version=go1.20.8 http.request.host="kube-image-keeper-registry:5000" http.request.id=256ac210-68f4-4e14-a212-6358d6743b07 http.request.method=HEAD http.request.remoteaddr="10.2.5.109:54706" http.request.uri="/v2/docker.io/bitnami/kubectl/manifests/1.31" http.request.useragent="go-containerregistry/v0.20.2" http.response.contenttype="application/json; charset=utf-8" http.response.duration=3.226962ms http.response.status=500 http.response.written=104 vars.name="docker.io/bitnami/kubectl" vars.reference=1.31 
10.2.5.109 - - [24/Mar/2025:19:43:00 +0000] "HEAD /v2/docker.io/bitnami/kubectl/manifests/1.31 HTTP/1.1" 500 104 "" "go-containerregistry/v0.20.2"
```

But when i create User with accesskey and secretAccess key everything is fine.
Can i somehow use Role without creating User with AccessKeys?

**Comment by grzegorzgniadekrespo** [comment]
OK. if someone need to use approach like that 
1. 
```
serviceAccount:
  annotations:
      eks.amazonaws.com/role-arn: arn:aws:iam::1112222333444:role/kuik-role
registry:
  image:
    repository: "ghcr.io/distribution/distribution"
    tag: "3.0.0-rc.1"
  serviceAccount:
    annotations:
      eks.amazonaws.com/role-arn: arn:aws:iam::1112222333444:role/kuik-role
  persistence:
    s3:
      region: "eu-central-1"
      bucket: kuik-testing-bucket
      forcepathstyle: "true" #can be false
controllers:
  serviceAccount:
    annotations:
      eks.amazonaws.com/role-arn: arn:aws:iam::1112222333444:role/kuik-role
```
We need to use latest distribution image which right now is 3.0.0-rc.1
https://github.com/distribution/distribution/releases/tag/v3.0.0-rc.1
Then on your role we need to add atleast
```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Action": [
                "ecr:GetAuthorizationToken",
                "ecr:BatchCheckLayerAvailability",
                "ecr:GetDownloadUrlForLayer",
                "ecr:GetRepositoryPolicy",
                "ecr:DescribeRepositories",
                "ecr:ListImages",
                "ecr:DescribeImages",
                "ecr:BatchGetImage",
                "ecr:GetLifecyclePolicy",
                "ecr:GetLifecyclePolicyPreview",
                "ecr:ListTagsForResource",
                "ecr:DescribeImageScanFindings"
            ],
            "Resource": "*"
        }
    ]
}
``` Or standard Policy Name AmazonEC2ContainerRegistryReadOnly. If someone got better idea let me know.
