### ISSUE TITLE
Garbage Collector docker/config.yml not found

### ISSUE THREAD

**Issue by grzegorzgniadekrespo** [enix/kube-image-keeper#498]
Hi my garbage collection job failed because of the log
Cluster Distribution: AWS EKS 1.30.0
EC2 Image: AL2@v20250203
ContainerD Version: containerd://1.7.25
Helm Chart Version: 1.12.0

Error Log
```
deployment "kube-image-keeper-registry" successfully rolled out
configuration error: open /etc/docker/registry/config.yml: no such file or directory
Usage:
  registry garbage-collect <config> [flags]

Flags:
  -m, --delete-untagged   delete manifests that are not currently referenced via tag
  -d, --dry-run           do everything except remove the blobs
  -h, --help              help for garbage-collect
  -q, --quiet             silence output
command terminated with exit code 1
```
Helm Chart Config
```
cachedImagesExpiryDelay: 7
controllers:
  replicas: 1
  serviceAccount:
    annotations:
      eks.amazonaws.com/role-arn: arn:aws:iam::1122223333:role/kuik-system@kuik-system
registry:
  image:
    repository: ghcr.io/distribution/distribution
    tag: 3.0.0-rc.4
  persistence:
    s3:
      bucket: kube-image-keeper
      forcepathstyle: "true"
      region: eu-central-1
  replicas: 2
  serviceAccount:
    annotations:
      eks.amazonaws.com/role-arn: arn:aws:iam::1122223333:role/kuik-system@kuik-system
serviceAccount:
  annotations:
      eks.amazonaws.com/role-arn: arn:aws:iam::1122223333:role/kuik-system@kuik-system
```
Can i repair it somehow?
Controller and registry works without problem, everything is cached and stored on S3. Webhook rewrites images tags on k8s resources.
