### ISSUE TITLE
Repository doesn't support regex for names

### ISSUE THREAD

**Issue by volker-fr** [enix/kube-image-keeper#509]
For mute able tags, you have to define each repository separately. It would be awesome if the repository name itself would support regex.

Example:
```
apiVersion: kuik.enix.io/v1alpha1
kind: Repository
metadata:
  name: all-repositories
spec:
  name: "*"
  updateInterval: 1h
  updateFilters:
    - 'latest'
```

Or `spec.name=docker.io/*`
