### ISSUE TITLE
No support of kubernetes.io/dockercfg secret type

### ISSUE THREAD

**Issue by gmykhailiuta** [enix/kube-image-keeper#96]
When using kube-image-keeper with GitLab Kubernetes Runner, the latter fails to pull any image with the error in corresponding kube-image-keeper proxy pod:
```
I0523 14:22:43.455311       1 server.go:113] "proxying request" repository="gitlab/gitlab-runner-helper" originRegistry="public.ecr.aws"
I0523 14:22:43.460211       1 server.go:116] "cached image is not available, proxying origin" originRegistry="public.ecr.aws" error="404 Not Found"
I0523 14:22:43.460239       1 server.go:200] "listing CachedImages" repositoryLabel="public.ecr.aws-gitlab-gitlab-runner-helper"
[GIN] 2023/05/23 - 14:22:43 | 401 |   30.418805ms |    10.23.24.186 | HEAD     "/v2/public.ecr.aws/gitlab/gitlab-runner-helper/manifests/x86_64-latest"
Error #01: invalid secret: missing .dockerconfigjson key
```
The root cause might be that GitLab runner uses `kubernetes.io/dockercfg` secret type of imagePullSecret for it's runner pods which has `.dockercfg` key in it instead of `.dockerconfigjson`.

Would it be possible to add support of `kubernetes.io/dockercfg` secret type?

**Comment by gmykhailiuta** [comment]
The above policy will not work if registry is used and it requires authentication. Below is a Kyverno Policy that deletes only gitlab-runner dockercfg registry secret. It's still possible to use gitlab registry by adding a static dockerconfigjson secret to imagePullSecrets list of runner pods.

```
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: glr-image-pull-secret
  annotations:
    policies.kyverno.io/title: Change Gitlab CI/CD Pods to ignore gitlab registry image pull secret
spec:
  validationFailureAction: Audit
  rules:
    - name: remove-image-pull-secrets-rule
      match:
        any:
          - resources:
              kinds:
                - Pod
              names:
                # Gitlab runner pods always have same prefix
                - "runner-*"
              namespaces:
                # Match all GLR namespaces
                - "prod-*-glr-*"
      preconditions:
        any:
          - key: "{{ request.object.spec.imagePullSecrets || '' }}"
            operator: NotEquals
            value: ""
      mutate:
        foreach:
          - list: "request.object.spec.imagePullSecrets"
            preconditions:
              any:
              - key: "{{ element.name }}"
                operator: Equals
                value: "runner-*"
            patchesJson6902: |-
              - path: /spec/imagePullSecrets/{{elementIndex}}
                op: remove
```
